steps:
#- name: 'gcr.io/cloud-builders/gcloud'
#  args:
#  - kms
#  - decrypt
#  - --ciphertext-file=.env.env
#  - --plaintext-file=.env
#  - --location=global
#  - --keyring=myproject
#  - --key=cloudbuild-env
#- name: 'bash'
#  args: ['echo', '$SSH-KEY']
- name: 'docker'
  args: [ 'build', '-t', 'finstreet/test-deployment:latest-$BRANCH_NAME', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=30062020 --password=$$PASSWORD']
  secretEnv: ['PASSWORD']
- name: 'docker'
  args: ['push', 'finstreet/test-deployment:latest-$BRANCH_NAME']
- name: 'docker'
  args: ['run', 'buildo/alpine-ssh', 'eval', '$(ssh-agent -s)']
secrets:
  - kmsKeyName: projects/indigo-history-283912/locations/global/keyRings/DOCKER_PASSWORD/cryptoKeys/DOCKER_PASSWORD
    secretEnv:
      PASSWORD: 'CiQADrWzp+CK21DHNqmwlCCmVWRBwwcYlkMr0Gminuzo+vQMdDASRwCLSVDh7qFeLHT8mIoPgx8TFaj3A4nBtWHMMyPN1Z7Rp/cXWaPklvz1Xlr8hCL+1KT8th5j7pOFxQkl2QHGAHvXSykUVkO1'
