steps:
    - name: 'docker'
      args: [ 'build', '-t', 'gcr.io/indigo-history-283912/quickstart-image', '.' ]
    - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: "bash"
      args:
        - "-c"
        - |
            ssh 94.130.59.82
